---
title: "Intro_main"
author: "Javier Fajardo"
date: "21/5/2018"
output: html_fragment
bibliography: biblio.bib
---

#### Latest News

**GCM compareR has been inestable for the last few days due to an increase in the amount of people that is using the app. Please, if you experience these issues, you may try again after a while. We are adjusting the server to improve the experience and fix stability in the shortest time possible.**


#### GCM compareR
GCM compareR is a web application developed to assist ecologists, conservationists and policy makers at understanding climate change scenarios and differences between Global Circulation Models (GCMs), and at assisting the triage of subsets of models in an objective and informed manner. GCM compareR is written in R and uses the web app development package Shiny. The code of this app can be find in the project's github, <a href = "https://github.com/marquetlab/GCM_compareR" target = "_blank">https://github.com/marquetlab/GCM_compareR</a>.  

Global Circulation Models (GCMs) are key to climate change research. Currently, scientists can chose from a large number of GCMs, as meteorological research centers worldwide have contributed more than 35 different GCMs for four distinct climate change scenarios as part of the Coupled Model Intercomparison Project Phase 5 (CMIP5; [@Taylor2012a]). Projections of future climate from all these models tell a common story, but the spread among them is also significant [@Zappa2017], which is an indicator of the irreducible uncertainty concerning any unverifiable future projection. For this reason, studies have shown that the choice of GCMs in modeling studies is an important source of variability in model outputs [@Thuiller2019]. The situation demands for workflows to help researchers exploring climate change scenarios to increase objectivity and repeatability in research and assure a well judged treatment of uncertainty [@Shepherd2018].

GCM compareR has been developed to play this role in helping researchers approaching GCMs in climate change studies and assist the selection of climate models. The app offers quick access to preloaded CMIP5 downscaled GCMs for the four RCPs [@VanVuuren2011] and allows users to compare their projections for future years. Comparison results are provided as scatterplots and maps where users may learn what makes different any GCM, identify groups of GCMs with similar characteristics (e.g. "colder" or "warmer" in their projection of temperature increase) and define storylines about the future climate [@Zappa2017].



***


#### Use of the App
GCM compareR contains tabs that might be used from left to right to define a comparison scenario, retrieve results and generate a report with them.  

- The *Intro* tab includes all the information needed to use the app. Move to the *Workflow* section to find full details about how to use the app, and go to *About* to find information about developers.  
- In the *Scenario* tab you will be able to set up a comparison scenario by making all choices: select the GCMs you would like to compare, pick a climate change scenario (year of projection, RCP...) and set the geographic extent of your analysis. Use the *Analyse* button on this tab to trigger the start of the analyses.  
- The tabs *Explore selected GCMs*, *Variation from present* and *Variation among futures* will display the results after the calculation is completed. Finally, *Report* will download a report with all the figures produced and some explanatory text.

***

#### Lastest news

> - Release of GCM compareR (Sep 26, 2018)

***

#### Citation  
Please, if you use GCM compareR as part of your research, cite the app as:  

>Fajardo, J, Corcoran, D., Roehrdanz, P, Hannah, P, Marquet, P (2019) GCM compareR: A web application to assess differences and assist in the selection of global circulation models for climate change research (in prep).
  
***
  
#### Contact us
Please, email derek.corcoran.barrios@gmail.com with any question of create an issue on <a href = "https://github.com/marquetlab/GCM_compareR" target = "_blank">github</a>.
  
***
  
#### References



